### ISSUE TITLE
support horizontal scaling?

### ISSUE THREAD

**Issue by shushenghong** [inlivedev/sfu#2]
one room on different server

**Comment by tyohan** [comment]
@shushenghong Currently, the library does not provide it. We're currently working to enable it on our[ cloud API](https://inlive.app/realtime-interactive). 

But you can develop the capability without changing the code of this library. This library has an extension API that can be used to develop a horizontal scaling extension. You can see how to use the extension API on [this test](https://github.com/inlivedev/sfu/blob/main/iext_test.go). 

To do it, when a room receives a get room request and does not find it locally, it will ask other servers if a server has it. If a server responds that they have it, the server who got the room request should create the same room in the server and then get all tracks from that remote room.

The API documentation for developing an extension will be coming later. In the meantime, you can use their test for your reference.
